-- 主键约束
ALTER TABLE apc_provenance ADD PRIMARY KEY (apc_provenance_id);
ALTER TABLE author ADD PRIMARY KEY (author_id);
ALTER TABLE author_alternative_name ADD PRIMARY KEY (author_id, alternative_name_seq);
ALTER TABLE author_institution ADD PRIMARY KEY (author_id, institution_seq);
ALTER TABLE author_institution_year ADD PRIMARY KEY (author_id, institution_seq, year_seq);
ALTER TABLE author_last_known_institution ADD PRIMARY KEY (author_id, last_known_institution_seq);
ALTER TABLE author_position ADD PRIMARY KEY (author_position_id);
ALTER TABLE citation ADD PRIMARY KEY (citing_work_id, reference_seq);
ALTER TABLE city ADD PRIMARY KEY (geonames_city_id);
ALTER TABLE concept ADD PRIMARY KEY (concept_id);
ALTER TABLE concept_ancestor ADD PRIMARY KEY (concept_id, ancestor_concept_seq);
ALTER TABLE concept_international_description ADD PRIMARY KEY (concept_id, language_code);
ALTER TABLE concept_international_name ADD PRIMARY KEY (concept_id, language_code);
ALTER TABLE concept_related ADD PRIMARY KEY (concept_id, related_concept_seq);
ALTER TABLE concept_umls_aui ADD PRIMARY KEY (concept_id, umls_aui_seq);
ALTER TABLE concept_umls_cui ADD PRIMARY KEY (concept_id, umls_cui_seq);
ALTER TABLE country ADD PRIMARY KEY (country_iso_alpha2_code);
ALTER TABLE data_source ADD PRIMARY KEY (data_source_id);
ALTER TABLE doi_registration_agency ADD PRIMARY KEY (doi_registration_agency_id);
ALTER TABLE domain ADD PRIMARY KEY (domain_id);
ALTER TABLE domain_alternative_name ADD PRIMARY KEY (domain_id, alternative_name_seq);
ALTER TABLE domain_field ADD PRIMARY KEY (domain_id, field_seq);
ALTER TABLE domain_sibling ADD PRIMARY KEY (domain_id, sibling_domain_seq);
ALTER TABLE field ADD PRIMARY KEY (field_id);
ALTER TABLE field_alternative_name ADD PRIMARY KEY (field_id, alternative_name_seq);
ALTER TABLE field_sibling ADD PRIMARY KEY (field_id, sibling_field_seq);
ALTER TABLE field_subfield ADD PRIMARY KEY (field_id, subfield_seq);
ALTER TABLE fulltext_origin ADD PRIMARY KEY (fulltext_origin_id);
ALTER TABLE funder ADD PRIMARY KEY (funder_id);
ALTER TABLE funder_alternative_name ADD PRIMARY KEY (funder_id, alternative_name_seq);
ALTER TABLE funder_publisher ADD PRIMARY KEY (funder_id, publisher_seq);
ALTER TABLE institution ADD PRIMARY KEY (institution_id);
ALTER TABLE institution_acronym ADD PRIMARY KEY (institution_id, acronym_seq);
ALTER TABLE institution_alternative_name ADD PRIMARY KEY (institution_id, alternative_name_seq);
ALTER TABLE institution_associated ADD PRIMARY KEY (institution_id, associated_institution_seq);
ALTER TABLE institution_funder ADD PRIMARY KEY (institution_id, funder_seq);
ALTER TABLE institution_international_name ADD PRIMARY KEY (institution_id, language_code);
ALTER TABLE institution_lineage ADD PRIMARY KEY (institution_id, lineage_institution_seq);
ALTER TABLE institution_publisher ADD PRIMARY KEY (institution_id, publisher_seq);
ALTER TABLE institution_relationship_type ADD PRIMARY KEY (institution_relationship_type_id);
ALTER TABLE institution_repository ADD PRIMARY KEY (institution_id, repository_seq);
ALTER TABLE institution_type ADD PRIMARY KEY (institution_type_id);
ALTER TABLE keyword ADD PRIMARY KEY (keyword_id);
ALTER TABLE license ADD PRIMARY KEY (license_id);
ALTER TABLE mesh_descriptor ADD PRIMARY KEY (mesh_descriptor_ui);
ALTER TABLE mesh_qualifier ADD PRIMARY KEY (mesh_qualifier_ui);
ALTER TABLE oa_status ADD PRIMARY KEY (oa_status_id);
ALTER TABLE publisher ADD PRIMARY KEY (publisher_id);
ALTER TABLE publisher_alternative_name ADD PRIMARY KEY (publisher_id, alternative_name_seq);
ALTER TABLE publisher_country ADD PRIMARY KEY (publisher_id, country_seq);
ALTER TABLE raw_affiliation_string ADD PRIMARY KEY (raw_affiliation_string_id);
ALTER TABLE raw_author_name ADD PRIMARY KEY (raw_author_name_id);
ALTER TABLE region ADD PRIMARY KEY (region_id);
ALTER TABLE source ADD PRIMARY KEY (source_id);
ALTER TABLE source_alternative_title ADD PRIMARY KEY (source_id, alternative_title_seq);
ALTER TABLE source_apc_price ADD PRIMARY KEY (source_id, apc_price_seq);
ALTER TABLE source_issn ADD PRIMARY KEY (source_id, issn_seq);
ALTER TABLE source_society ADD PRIMARY KEY (source_id, society_seq);
ALTER TABLE source_type ADD PRIMARY KEY (source_type_id);
ALTER TABLE subfield ADD PRIMARY KEY (subfield_id);
ALTER TABLE subfield_alternative_name ADD PRIMARY KEY (subfield_id, alternative_name_seq);
ALTER TABLE subfield_sibling ADD PRIMARY KEY (subfield_id, sibling_subfield_seq);
ALTER TABLE subfield_topic ADD PRIMARY KEY (subfield_id, topic_seq);
ALTER TABLE sustainable_development_goal ADD PRIMARY KEY (sustainable_development_goal_id);
ALTER TABLE topic ADD PRIMARY KEY (topic_id);
ALTER TABLE topic_keyword ADD PRIMARY KEY (topic_id, keyword_seq);
ALTER TABLE topic_sibling ADD PRIMARY KEY (topic_id, sibling_topic_seq);
ALTER TABLE version ADD PRIMARY KEY (version_id);
ALTER TABLE work ADD PRIMARY KEY (work_id);
ALTER TABLE work_abstract ADD PRIMARY KEY (work_id);
ALTER TABLE work_affiliation ADD PRIMARY KEY (work_id, affiliation_seq);
ALTER TABLE work_affiliation_institution ADD PRIMARY KEY (work_id, affiliation_seq, institution_seq);
ALTER TABLE work_author ADD PRIMARY KEY (work_id, author_seq);
ALTER TABLE work_author_affiliation ADD PRIMARY KEY (work_id, author_seq, affiliation_seq);
ALTER TABLE work_author_country ADD PRIMARY KEY (work_id, author_seq, country_seq);
ALTER TABLE work_concept ADD PRIMARY KEY (work_id, concept_seq);
ALTER TABLE work_data_source ADD PRIMARY KEY (work_id, data_source_seq);
ALTER TABLE work_detail ADD PRIMARY KEY (work_id);
ALTER TABLE work_grant ADD PRIMARY KEY (work_id, grant_seq);
ALTER TABLE work_keyword ADD PRIMARY KEY (work_id, keyword_seq);
ALTER TABLE work_location ADD PRIMARY KEY (work_id, location_seq);
ALTER TABLE work_mesh ADD PRIMARY KEY (work_id, mesh_seq);
ALTER TABLE work_reference ADD PRIMARY KEY (work_id, reference_seq);
ALTER TABLE work_related ADD PRIMARY KEY (work_id, related_work_seq);
ALTER TABLE work_sustainable_development_goal ADD PRIMARY KEY (work_id, sustainable_development_goal_seq);
ALTER TABLE work_title ADD PRIMARY KEY (work_id);
ALTER TABLE work_topic ADD PRIMARY KEY (work_id, topic_seq);
ALTER TABLE work_type ADD PRIMARY KEY (work_type_id);
